scanning = "ni"
scopeless = false
sample_rate = 40000
notifier = "none"
array_ram_MB = 5000

[voxel_size]
x = 0.3
y = 0.3

[default_paths]
data = "C:\\Users\\B0067-WS-3"
presets = "C:\\Users\\B0067-WS-3\\presets"
log = "C:\\Users\\B0067-WS-3\\logs"
scope_instructions = ""

[piezo]
scale = 0.025

[email]
user = "foo"
password = "foo"

[camera]
id = 0
name = "photometrics"
max_sensor_resolution = [ 2960, 5056,]
default_exposure = 20
default_binning = 1

[light_source]
name = "mock"
port = "COM4"
intensity_units = "mock"

[shutter]
name = "mock"
port = "PXI6259/port0/line0"

[external_communication]
name = "stytra"
address = "tcp://127.0.0.1:5555"

[notifier_options]

[camera.photometrics]
readout_port = 2
speed_table_index = 0
gain_index = 1
exp_out_mode = 4

[z_board.read]
channel = "PXI6259/ai0:0"
min_val = 0
max_val = 10

[z_board.write]
channel = "PXI6259/ao0:3"
min_val = -5
max_val = 10

[z_board.sync]
channel = "/PXI6259/ao/StartTrigger"

[xy_board.write]
channel = "PXI6733/ao0:1"
min_val = -5
max_val = 10
